#include "csapp.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>

//required by windows to clean up. 
void init_winsock() {
#ifdef _WIN32
    WSADATA wsa;
    if (WSAStartup(MAKEWORD(2, 2), &wsa) != 0) {
        fprintf(stderr, "WSAStartup failed\n");
        exit(1);
    }
#endif
}

void cleanup_winsock() {
#ifdef _WIN32
    WSACleanup();
#endif
}
// ───────────────────────────────────────────────────────────

// close, handles windows and linux
void close_socket(socket_t fd) {
#ifdef _WIN32
    closesocket(fd);
#else
    close(fd);
#endif
}

// ───────────────────────────────────────────────────────────

// what is rio? ── robust, always get what you asked for, not a partial read.
//                 buffered, it's not making a network call every time you read a byte


//the following was generated by AI, I was unable to retrieve the prompt because I was not
//logged into my account when I asked the prompt, but i essentially asked for help making.
// a semi replica of csapp.

//however, all the comments are my own.


//the internal refill, checks if buffer has data. never called directly.
static ssize_t rio_read(rio_t *rp, char *usrbuf, size_t n) {
    while (rp->rio_cnt <= 0) {
#ifdef _WIN32
        rp->rio_cnt = recv(rp->rio_fd, rp->rio_buf, RIO_BUFSIZE, 0);
        if (rp->rio_cnt == SOCKET_ERROR) return -1;
#else
        rp->rio_cnt = (int)recv(rp->rio_fd, rp->rio_buf, RIO_BUFSIZE, 0);
        if (rp->rio_cnt < 0) return -1;
#endif
        if (rp->rio_cnt == 0) return 0;  // EOF
        rp->rio_bufptr = rp->rio_buf;
    }

    size_t cnt = (n < (size_t)rp->rio_cnt) ? n : (size_t)rp->rio_cnt;
    memcpy(usrbuf, rp->rio_bufptr, cnt);
    rp->rio_bufptr += cnt;
    rp->rio_cnt    -= (int)cnt;
    return (ssize_t)cnt;
}

//zeros everything out and links to socket.
void rio_readinitb(rio_t *rp, socket_t fd) {
    rp->rio_fd     = fd;
    rp->rio_cnt    = 0;
    rp->rio_bufptr = rp->rio_buf;
}

//reads one fill line from the socket, keeps going until new line.
//what server and client uses to recieve messages
ssize_t rio_readlineb(rio_t *rp, void *usrbuf, size_t maxlen) {
    char  c;
    char *bufp   = (char *)usrbuf;
    ssize_t n    = 0;
    ssize_t rc;

    for (size_t i = 1; i < maxlen; i++) {
        rc = rio_read(rp, &c, 1);
        if (rc == 1) {
            *bufp++ = c;
            n++;
            if (c == '\n') break;
        } else if (rc == 0) {
            break;
        } else {
            return -1;
        }
    }
    *bufp = '\0';
    return n;
}

//server only, creates a socket, binds it to a port number and starts listening.
ssize_t rio_writen(socket_t fd, const void *usrbuf, size_t n) {
    size_t      nleft = n;
    const char *bufp  = (const char *)usrbuf;

    while (nleft > 0) {
#ifdef _WIN32
        int nwritten = send(fd, bufp, (int)nleft, 0);
        if (nwritten == SOCKET_ERROR) return -1;
#else
        ssize_t nwritten = send(fd, bufp, nleft, 0);
        if (nwritten < 0) return -1;
#endif
        nleft -= (size_t)nwritten;
        bufp  += nwritten;
    }
    return (ssize_t)n;
}

// ──────────────────────────────────────────────────────────

//server only, creates a socket, binds to port number and starts listening for connections.
socket_t open_listenfd(int port) {
    socket_t listenfd = socket(AF_INET, SOCK_STREAM, 0);
    if (listenfd == INVALID_SOCK) {
        perror("socket");
        return INVALID_SOCK;
    }

    int optval = 1;
    setsockopt(listenfd, SOL_SOCKET, SO_REUSEADDR,
               (const char *)&optval, sizeof(optval));

    struct sockaddr_in serveraddr;
    memset(&serveraddr, 0, sizeof(serveraddr));
    serveraddr.sin_family      = AF_INET;
    serveraddr.sin_addr.s_addr = htonl(INADDR_ANY);
    serveraddr.sin_port        = htons((unsigned short)port);

    if (bind(listenfd, (struct sockaddr *)&serveraddr, sizeof(serveraddr)) < 0) {
        perror("bind");
        close_socket(listenfd);
        return INVALID_SOCK;
    }

    if (listen(listenfd, 10) < 0) {
        perror("listen");
        close_socket(listenfd);
        return INVALID_SOCK;
    }

    return listenfd;
}

// ──────────────────────────────────────────────────────────

//client only, looks up servers address and connects to it. returns socket ready to talk to server.
socket_t open_clientfd(const char *hostname, int port) {
    struct addrinfo hints, *result;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family   = AF_INET;
    hints.ai_socktype = SOCK_STREAM;

    char portstr[8];
    snprintf(portstr, sizeof(portstr), "%d", port);

    if (getaddrinfo(hostname, portstr, &hints, &result) != 0) {
        fprintf(stderr, "getaddrinfo failed\n");
        return INVALID_SOCK;
    }

    socket_t clientfd = socket(result->ai_family,
                                result->ai_socktype,
                                result->ai_protocol);
    if (clientfd == INVALID_SOCK) {
        freeaddrinfo(result);
        perror("socket");
        return INVALID_SOCK;
    }

    if (connect(clientfd, result->ai_addr, (int)result->ai_addrlen) < 0) {
        freeaddrinfo(result);
        close_socket(clientfd);
        perror("connect");
        return INVALID_SOCK;
    }

    freeaddrinfo(result);
    return clientfd;
}
